# .github/workflows/scrape.yml

name: Run Main Anime Scraper

on:
  schedule:
    - cron: '0 */12 * * *' # Jalankan setiap 12 jam
  workflow_dispatch: # Izinkan untuk dijalankan manual

jobs:
  scrape:
    runs-on: ubuntu-latest

    # Berikan izin untuk push ke repo
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium
          
      - name: Run main scraper script
        run: python scraper.py
      
      # Commit dan Push hasil JSON ke repositori
      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add anime_database.json
          # Commit hanya jika ada perubahan
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update latest anime data with episodes" -a
          fi
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Sesuaikan nama branch Anda
