name: Scrape Latest Anime

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Langkah BARU: Instal browser yang dibutuhkan oleh Playwright
      - name: Install Playwright Browsers
        run: playwright install --with-deps chromium
          
      - name: Run scraper
        run: python scraper.py

      - name: Commit results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # Hanya commit jika file json ada dan memiliki perubahan
          if [ -f "latest_anime.json" ]; then
            git add latest_anime.json
            if git diff-index --quiet HEAD; then
              echo "No changes to commit."
            else
              git commit -m "Update latest anime data" -a
            fi
          else
            echo "latest_anime.json not found. Skipping commit."
          fi
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # Sesuaikan dengan nama branch Anda
